manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      # v4.0.0 does not have support for adc dma on stm32f1x,
      # it have been added on main, so for not just use main.
      # Whan a release is available with the support, it should be used.
      #revision: v4.1.0
      revision: main
      clone-depth: 1
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - picolibc
          - segger
          - hal_stm32
    - name: ws2812-stm32
      path: modules/ws2812-stm32
      revision: v1.0
      url: https://github.com/PChristoffersen/zephyr-ws2812-stm32.git
  self:
    path: application
